### ISSUE TITLE
Manual Save of DOC files

### ISSUE THREAD

**Issue by SmayanaReddy** [SmayanaReddy/auto_anki#3]
With new enhancement to support    .docs  files, we are also required to save file

**Comment by SmayanaReddy** [comment]
@Harikrishnaselvaraj Can you think of alternative/ workaround for this issue ?

**Comment by Harikrishnaselvaraj** [comment]
@SmayanaReddy This requires changes in couple of python files to be changed/major change , since the JSON format for processing of both the files are different.

**Comment by gokul-koganti** [comment]
@Harikrishnaselvaraj  Is this issue resolved?

**Comment by Harikrishnaselvaraj** [comment]
@SmayanaReddy  This issue is fixed now.
