### ISSUE TITLE
Problems concerning exiting the ui

### ISSUE THREAD

**Issue by gokul-koganti** [SmayanaReddy/auto_anki#6]
@User is unable to exit the UI. Termination of processing being required to exit the flow @SmayanaReddy

**Comment by SmayanaReddy** [comment]
I think adding an "exit" button to ui would be a better way to handle this issue. @gokul-koganti what do think?

**Comment by gokul-koganti** [comment]
@SmayanaReddy, I think we can go ahead with that. It would be a considerable improvement over the current termination flow.

**Comment by SmayanaReddy** [comment]
Fixed
